version: "3.4"
services:
  mongo:
    image: mongo:4.2.0-bionic
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - fyndnet
    volumes:
      - $mongoSharedVolume:/data/db
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - fyndnet
    volumes:
      - "$redisSharedVolume:/data"
networks:
  fyndnet:
    external:
      name: fyndnet
