services:
  short_url-local-srvr:
    build:
      context: ../.
      dockerfile: Dockerfile
    networks:
      - bithash
    volumes:
      - ../.:/bithash/short_url
    environment:
      - MODE=server
    env_file:
      - ".env"
    tty: true
    ports:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://short_url-local-srvr:8000/healthz"]
      interval: 30s  # How often to run the check
      retries: 3      # Number of retries before marking the container as unhealthy
      start_period: 10s  # Grace period for containers to initialize
      timeout: 3s     # How long to wait for the health check to complete

  mongo:
    image: mongo:7.0-rc
    container_name: bithash_mongo
    hostname: bithash_mongo
    ports:
      - "27017:27017"
    networks:
      - bithash
    volumes:
#      - $mongoSharedVolume:/data/db # use this if using via sh file
      - H:\dev\mongo:/data/db # for windows

  redis:
    image: redis:7.2.3-alpine3.18
    container_name: bithash_redis
    hostname: bithash_redis
    ports:
      - "6379:6379"
    networks:
      - bithash
    volumes:
#     - "$redisSharedVolume:/data" # use this if using via sh file
      - H:\dev\redis:/data:/data  # for windows
    
  nginx:
    image: nginx:stable-perl
    volumes:
      - H:\dev\shortURL\local_setup\nginx.conf:/etc/nginx/nginx.conf:ro  # for windows
    depends_on:
      - short_url-local-srvr
    ports:
      - "80:80"
    networks:
      - bithash

networks:
  bithash:
    external:
      name: bithash
