version: '2'
services:
  app:
    build:
      context: ../.
      dockerfile: Dockerfile
    hostname: app
    container_name: app
    networks:
      - bithash
    volumes:
      - ../.:/bithash/short_url
    environment:
      - MODE=server
    env_file:
      - ".env"
    tty: true
    ports:
      - "8000:8000"

  
networks:
  bithash:
    external:
      name: bithash
