receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"  # Export metrics in Prometheus format

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
